version: '3.6'
services:
  profile:
    build: ./auth
    ports:
      - "5004:5004"
    links:
      - app-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ht-home-pro.local:5433/vehicle-app?currentSchema=profiles_db
      - MYAPP_JDBC_USER=postgres
      - DB_PASSWORD=root

  app-db:
    build: ./postgres
    restart: always
    environment:
      - DATABASE_HOST=ht-home-pro.local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5433:5432"