pipeline {
    agent any

    environment {
        REMOTE_ADDRESS = "REPLACE_WITH_REMOTE_ADDRESS"
    }

    stages {
		stage ("Build stage") {
        	steps {
            	sh 'gradle :gateway:clean :gateway:build'
            }
        }
        stage('Unit Tests') {
            steps {
                sh 'gradle :gateway:test'
            }
            post {
                always {
                    junit '**/build/test-results/test/TEST-*.xml'
                }
            }
        }
    }
}