pipeline {
    agent any

    triggers{
    }

    options {
    }

    environment {
        REMOTE_ADDRESS = "REPLACE_WITH_REMOTE_ADDRESS"
    }

    stages {
		stage ("build gradle") {
        	steps {
            	sh './gradlew clean build'
            }
        }
    }


}