server:
  port: 5001

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: authService
          uri: http://localhost:5004
          predicates:
            - Path=/auth/**
        - id: servService
          uri: http://localhost:5100
          predicates:
            - Path=/serv/**

jwt:
  secret: secret_secret_secret_secret_secret_secret
  expiration: 60
  crsfToken: 123qdq!