server:
  port: 5001

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: authService
          uri: http://localhost:5010
          predicates:
            - Path=/auth/**

application:
  cors:
    allowed-origins:
      - "*"
