logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

server:
  port: 5004

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/vehicle-app?currentSchema=user_db
    username: postgres
    password: ${db_password}
  flyway:
    url: jdbc:postgresql://localhost:5432/vehicle-app?currentSchema=user_db
    user: postgres
    password: ${db_password}

jwt:
  secret: ${jwt_secret}
  expiration: 86400