logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

server:
  port: 5004

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/vehicle-app?currentSchema=user_db
    username: postgres
    password: root
  flyway:
    url: jdbc:postgresql://localhost:5432/vehicle-app?currentSchema=user_db
    user: postgres
    password: root

jwt:
  secret: secret_secret_secret_secret_secret_secret
  expiration: 86400

db_password: root
jwt_secret: secret_secret_secret_secret_secret_secret
